"""Per-major roadmap classifier based on explicit module dependency graphs.

Each major is modeled as a DAG of learning modules.  A module represents a
conceptual component of the discipline (e.g. "数学基础", "机器学习").  Modules
are connected by prerequisite edges that respect the actual structure of the
field.  Courses are assigned to the module whose content they support.
"""

from typing import Optional


# ---------------------------------------------------------------------------
# Module dependency graph configuration for every major.
# ---------------------------------------------------------------------------
# For each major:
#   modules           - list of {id, name, depends_on: [id, ...]}
#   course_to_module  - keyword (substring) -> module id
#   fallback_module   - module id for courses that match no keyword
# ---------------------------------------------------------------------------

ROADMAP_MODULES: dict[str, dict] = {
    # ---------------------------------------------------------------------- AI
    "人工智能": {
        "modules": [
            {"id": "math", "name": "数学基础", "depends_on": []},
            {"id": "programming", "name": "编程与算法基础", "depends_on": ["math"]},
            {"id": "ai-intro", "name": "人工智能导论", "depends_on": ["programming"]},
            {"id": "ml", "name": "机器学习", "depends_on": ["ai-intro"]},
            {"id": "dl", "name": "深度学习与人工智能", "depends_on": ["ml"]},
            {"id": "systems", "name": "智能系统", "depends_on": ["ai-intro"]},
            {"id": "practice", "name": "人工智能系统实践", "depends_on": ["dl", "systems"]},
        ],
        "course_to_module": {
            "线性代数": "math",
            "概率统计": "math",
            "概率论": "math",
            "数理统计": "math",
            "微积分": "math",
            "数学分析": "math",
            "离散数学": "math",
            "ai中的数学": "math",
            "数学串珠": "math",
            "高等数学": "math",
            "程序设计": "programming",
            "计算概论": "programming",
            "数据结构": "programming",
            "算法导论": "programming",
            "算法设计与分析": "programming",
            "计算机系统导论": "programming",
            "编译原理": "programming",
            "理论计算机科学基础": "programming",
            "离散数学与结构": "programming",
            "人工智能引论": "ai-intro",
            "知识表达与学习": "ai-intro",
            "人工智能与商学": "ai-intro",
            "人工智能与社会科学": "ai-intro",
            "人工智能与音乐": "ai-intro",
            "人工智能伦理与治理": "ai-intro",
            "机器学习": "ml",
            "深度学习": "dl",
            "强化学习": "dl",
            "大语言模型": "dl",
            "认知与推理": "dl",
            "inference": "ml",
            "optimization methods": "ml",
            "信息论": "ml",
            "多智能体系统": "systems",
            "操作系统": "systems",
            "计算机网络": "systems",
            "计算机组织与体系结构": "systems",
            "并行与分布式计算": "systems",
            "微电子与电路基础": "systems",
            "机器人学概论": "systems",
            "自动控制理论": "systems",
            "人工智能系统实践": "practice",
            "算法设计与分析": "practice",
            "程序设计实习": "practice",
            "人工智能引论实践课": "practice",
            "人工智能初级研讨班": "practice",
            "新生教育实践课程": "practice",
            "书院成长课程": "practice",
        },
        "fallback_module": "dl",
    },

    # ---------------------------------------------------------------------- CS
    "计算机科学与技术": {
        "modules": [
            {"id": "math", "name": "数学基础", "depends_on": []},
            {"id": "programming", "name": "程序设计", "depends_on": ["math"]},
            {"id": "data-structures", "name": "数据结构与算法", "depends_on": ["programming"]},
            {"id": "computer-systems", "name": "计算机系统", "depends_on": ["data-structures"]},
            {"id": "os-network", "name": "操作系统与网络", "depends_on": ["computer-systems"]},
            {"id": "database", "name": "数据库与分布式", "depends_on": ["computer-systems"]},
            {"id": "software-engineering", "name": "软件工程与安全", "depends_on": ["os-network", "database"]},
            {"id": "ai-frontier", "name": "人工智能与前沿", "depends_on": ["data-structures"]},
            {"id": "practice", "name": "专业实践", "depends_on": ["software-engineering", "ai-frontier"]},
        ],
        "course_to_module": {
            "高等数学": "math",
            "线性代数": "math",
            "概率统计": "math",
            "离散数学": "math",
            "数学分析": "math",
            "calculus": "math",
            "linear algebra": "math",
            "probability": "math",
            "discrete mathematics": "math",
            "programming": "programming",
            "程序设计": "programming",
            "计算概论": "programming",
            "introduction to computer": "programming",
            "computer science and programming": "programming",
            "programming in python": "programming",
            "programming in java": "programming",
            "intermediate programming": "programming",
            "advanced programming": "programming",
            "数据结构": "data-structures",
            "算法": "data-structures",
            "algorithms": "data-structures",
            "data structures": "data-structures",
            "introduction to algorithms": "data-structures",
            "algorithm design and analysis": "data-structures",
            "计算机系统": "computer-systems",
            "计算机组成": "computer-systems",
            "体系结构": "computer-systems",
            "computer systems": "computer-systems",
            "computer organization": "computer-systems",
            "computer architecture": "computer-systems",
            "computation structures": "computer-systems",
            "fundamentals of computer systems": "computer-systems",
            "操作系统": "os-network",
            "operating systems": "os-network",
            "计算机网络": "os-network",
            "computer networks": "os-network",
            "networks": "os-network",
            "数据库": "database",
            "database": "database",
            "分布式": "database",
            "distributed computing": "database",
            "distributed systems": "database",
            "distributed database": "database",
            "软件工程": "software-engineering",
            "software engineering": "software-engineering",
            "software design": "software-engineering",
            "software testing": "software-engineering",
            "object-oriented": "software-engineering",
            "programming languages": "software-engineering",
            "信息安全": "software-engineering",
            "网络安全": "software-engineering",
            "密码学": "software-engineering",
            "information security": "software-engineering",
            "computer security": "software-engineering",
            "information assurance": "software-engineering",
            "cryptography": "software-engineering",
            "人工智能": "ai-frontier",
            "机器学习": "ai-frontier",
            "深度学习": "ai-frontier",
            "artificial intelligence": "ai-frontier",
            "machine learning": "ai-frontier",
            "deep learning": "ai-frontier",
            "computer vision": "ai-frontier",
            "natural language processing": "ai-frontier",
            "computer graphics": "ai-frontier",
            "human-computer interaction": "ai-frontier",
            "hci": "ai-frontier",
            "可视化": "ai-frontier",
            "大数据": "ai-frontier",
            "云计算": "ai-frontier",
            "区块链": "ai-frontier",
            "物联网": "ai-frontier",
            "big data": "ai-frontier",
            "cloud computing": "ai-frontier",
            "blockchain": "ai-frontier",
            "internet of things": "ai-frontier",
            "quantum computing": "ai-frontier",
            "机器人": "ai-frontier",
            "practice": "practice",
            "实习": "practice",
            "研讨班": "practice",
            "项目": "practice",
            "毕业设计": "practice",
            "internship": "practice",
            "practicum": "practice",
            "project": "practice",
            "seminar": "practice",
            "workshop": "practice",
        },
        "fallback_module": "ai-frontier",
    },

    # ---------------------------------------------------------------------- Chemistry
    "化学": {
        "modules": [
            {"id": "math-physics", "name": "数学物理基础", "depends_on": []},
            {"id": "general-chemistry", "name": "普通化学", "depends_on": ["math-physics"]},
            {"id": "core-chemistry", "name": "化学核心", "depends_on": ["general-chemistry"]},
            {"id": "advanced-chemistry", "name": "高级化学与交叉", "depends_on": ["core-chemistry"]},
            {"id": "chemical-engineering", "name": "化工与材料", "depends_on": ["core-chemistry"]},
            {"id": "laboratory", "name": "化学实验", "depends_on": ["core-chemistry"]},
        ],
        "course_to_module": {
            "高等数学": "math-physics",
            "线性代数": "math-physics",
            "概率统计": "math-physics",
            "数学分析": "math-physics",
            "力学": "math-physics",
            "电磁学": "math-physics",
            "光学": "math-physics",
            "热学": "math-physics",
            "普通物理": "math-physics",
            "计算概论": "math-physics",
            "基础物理实验": "math-physics",
            "普通化学": "general-chemistry",
            "大学化学": "general-chemistry",
            "化学中的数学": "general-chemistry",
            "理论与计算化学导论": "general-chemistry",
            "生命化学基础": "general-chemistry",
            "应用化学基础": "general-chemistry",
            "无机化学": "core-chemistry",
            "有机化学": "core-chemistry",
            "分析化学": "core-chemistry",
            "物理化学": "core-chemistry",
            "化学生物学": "core-chemistry",
            "f区元素化学": "core-chemistry",
            "中级无机化学": "core-chemistry",
            "中级有机化学": "core-chemistry",
            "中级分析化学": "core-chemistry",
            "中级物理化学": "core-chemistry",
            "定量分析化学": "core-chemistry",
            "简明有机化学": "core-chemistry",
            "物理有机化学": "core-chemistry",
            "生物物理化学": "core-chemistry",
            "催化化学": "core-chemistry",
            "分子光谱": "core-chemistry",
            "表面物理化学": "core-chemistry",
            "凝聚态光谱": "core-chemistry",
            "化学反应动力学": "core-chemistry",
            "化学生物学": "core-chemistry",
            "学术道德规范与科技写作": "core-chemistry",
            "化学信息检索": "core-chemistry",
            "材料化学": "advanced-chemistry",
            "材料物理": "advanced-chemistry",
            "纳米化学": "advanced-chemistry",
            "高分子化学": "advanced-chemistry",
            "高分子物理": "advanced-chemistry",
            "高性能聚合物材料": "advanced-chemistry",
            "多晶x射线衍射": "advanced-chemistry",
            "核能材料": "advanced-chemistry",
            "放射化学": "advanced-chemistry",
            "辐射化学": "advanced-chemistry",
            "理论与计算化学": "advanced-chemistry",
            "群论与化学": "advanced-chemistry",
            "结构化学": "advanced-chemistry",
            "立体化学": "advanced-chemistry",
            "界面化学": "advanced-chemistry",
            "胶体化学": "advanced-chemistry",
            "色谱质谱分析": "advanced-chemistry",
            "核磁共振波谱分析": "advanced-chemistry",
            "环境化学": "advanced-chemistry",
            "药物化学导论": "advanced-chemistry",
            "三维成像前沿": "advanced-chemistry",
            "交叉中的化学科学": "advanced-chemistry",
            "今日化学": "advanced-chemistry",
            "改变世界的药物分子": "advanced-chemistry",
            "计算机在化学化工中的应用": "advanced-chemistry",
            "化工基础": "chemical-engineering",
            "化工新概念": "chemical-engineering",
            "化工制图": "chemical-engineering",
            "电化学": "chemical-engineering",
            "能源": "chemical-engineering",
            "普通化学实验": "laboratory",
            "无机化学实验": "laboratory",
            "有机化学实验": "laboratory",
            "分析化学实验": "laboratory",
            "物理化学实验": "laboratory",
            "中级有机化学实验": "laboratory",
            "中级物理化学实验": "laboratory",
            "中级分析化学实验": "laboratory",
            "仪器分析实验": "laboratory",
            "化学生物学实验": "laboratory",
            "综合化学实验": "laboratory",
            "综合创新实验": "laboratory",
            "化学生物学整合实验": "laboratory",
            "化学整合科学实验": "laboratory",
            "化学应用与实践": "laboratory",
            "化学实验室安全技术": "laboratory",
        },
        "fallback_module": "advanced-chemistry",
    },

    # ---------------------------------------------------------------------- Physics
    "物理学": {
        "modules": [
            {"id": "math", "name": "数学基础", "depends_on": []},
            {"id": "classical-mechanics", "name": "经典力学", "depends_on": ["math"]},
            {"id": "em-optics-thermal", "name": "电磁学/光学/热学", "depends_on": ["math"]},
            {"id": "modern-physics", "name": "近代物理", "depends_on": ["classical-mechanics", "em-optics-thermal"]},
            {"id": "specialty", "name": "专业方向", "depends_on": ["modern-physics"]},
            {"id": "laboratory", "name": "物理实验", "depends_on": ["em-optics-thermal"]},
        ],
        "course_to_module": {
            "高等数学": "math",
            "线性代数": "math",
            "概率统计": "math",
            "数学物理方法": "math",
            "数学分析": "math",
            "复变函数": "math",
            "计算方法": "math",
            "计算概论": "math",
            "程序设计": "math",
            "力学": "classical-mechanics",
            "理论力学": "classical-mechanics",
            "电磁学": "em-optics-thermal",
            "电动力学": "em-optics-thermal",
            "光学": "em-optics-thermal",
            "应用光学": "em-optics-thermal",
            "物理光学": "em-optics-thermal",
            "热学": "em-optics-thermal",
            "热力学": "em-optics-thermal",
            "统计物理": "em-optics-thermal",
            "近代物理": "modern-physics",
            "原子物理": "modern-physics",
            "量子物理": "modern-physics",
            "量子力学": "modern-physics",
            "固体物理": "modern-physics",
            "凝聚态": "specialty",
            "粒子物理": "specialty",
            "核物理": "specialty",
            "宇宙学": "specialty",
            "半导体": "specialty",
            "电子学": "specialty",
            "微电子": "specialty",
            "计算物理": "specialty",
            "物理实验": "laboratory",
            "近代物理实验": "laboratory",
            "综合物理实验": "laboratory",
            "基础物理实验": "laboratory",
        },
        "fallback_module": "specialty",
    },

    # ---------------------------------------------------------------------- Math
    "数学与应用数学": {
        "modules": [
            {"id": "analysis", "name": "分析基础", "depends_on": []},
            {"id": "algebra-geometry", "name": "代数与几何", "depends_on": ["analysis"]},
            {"id": "probability", "name": "概率统计", "depends_on": ["analysis", "algebra-geometry"]},
            {"id": "applied-math", "name": "应用数学", "depends_on": ["analysis", "algebra-geometry", "probability"]},
            {"id": "topics", "name": "专题", "depends_on": ["applied-math"]},
        ],
        "course_to_module": {
            "数学分析": "analysis",
            "实变函数": "analysis",
            "复变函数": "analysis",
            "泛函分析": "analysis",
            "常微分方程": "analysis",
            "高等数学": "analysis",
            "解析几何": "analysis",
            "高等代数": "algebra-geometry",
            "线性代数": "algebra-geometry",
            "抽象代数": "algebra-geometry",
            "代数学": "algebra-geometry",
            "几何": "algebra-geometry",
            "拓扑": "algebra-geometry",
            "微分几何": "algebra-geometry",
            "概率论": "probability",
            "随机过程": "probability",
            "测度论": "probability",
            "数理统计": "probability",
            "回归分析": "probability",
            "多元统计": "probability",
            "时间序列": "probability",
            "偏微分方程": "applied-math",
            "动力系统": "applied-math",
            "微分方程": "applied-math",
            "数值分析": "applied-math",
            "计算方法": "applied-math",
            "科学计算": "applied-math",
            "运筹学": "applied-math",
            "优化": "applied-math",
            "博弈论": "applied-math",
            "控制论": "applied-math",
            "金融数学": "applied-math",
            "精算": "applied-math",
            "风险理论": "applied-math",
            "专题": "topics",
            "讨论班": "topics",
            "前沿": "topics",
            "选讲": "topics",
        },
        "fallback_module": "topics",
    },

    # ---------------------------------------------------------------------- Statistics
    "统计学": {
        "modules": [
            {"id": "math", "name": "数学基础", "depends_on": []},
            {"id": "probability", "name": "概率论", "depends_on": ["math"]},
            {"id": "mathematical-statistics", "name": "数理统计", "depends_on": ["probability"]},
            {"id": "statistical-computing", "name": "统计计算与机器学习", "depends_on": ["mathematical-statistics"]},
            {"id": "applied-statistics", "name": "应用统计", "depends_on": ["statistical-computing"]},
        ],
        "course_to_module": {
            "高等数学": "math",
            "线性代数": "math",
            "数学分析": "math",
            "概率论": "probability",
            "测度论": "probability",
            "随机过程": "probability",
            "数理统计": "mathematical-statistics",
            "统计推断": "mathematical-statistics",
            "回归分析": "mathematical-statistics",
            "方差分析": "mathematical-statistics",
            "抽样调查": "mathematical-statistics",
            "试验设计": "mathematical-statistics",
            "非参数统计": "mathematical-statistics",
            "统计计算": "statistical-computing",
            "贝叶斯计算": "statistical-computing",
            "计算统计": "statistical-computing",
            "蒙特卡洛": "statistical-computing",
            "机器学习": "statistical-computing",
            "数据挖掘": "statistical-computing",
            "统计学习": "statistical-computing",
            "金融统计": "applied-statistics",
            "经济统计": "applied-statistics",
            "计量经济": "applied-statistics",
            "金融时间序列": "applied-statistics",
            "生物统计": "applied-statistics",
            "医学统计": "applied-statistics",
            "生存分析": "applied-statistics",
            "数据科学": "applied-statistics",
            "大数据分析": "applied-statistics",
            "数据可视化": "applied-statistics",
        },
        "fallback_module": "applied-statistics",
    },

    # ---------------------------------------------------------------------- History
    "历史学": {
        "modules": [
            {"id": "methods", "name": "史学方法", "depends_on": []},
            {"id": "ancient-china", "name": "中国古代史", "depends_on": ["methods"]},
            {"id": "modern-china", "name": "中国近现代史", "depends_on": ["methods"]},
            {"id": "world-history", "name": "世界史", "depends_on": ["methods"]},
            {"id": "archaeology", "name": "考古文博", "depends_on": ["methods"]},
            {"id": "seminars", "name": "专题研讨", "depends_on": ["ancient-china", "modern-china", "world-history"]},
        ],
        "course_to_module": {
            "史学概论": "methods",
            "史学新生导学": "methods",
            "历史论文写作": "methods",
            "中国历史文选": "methods",
            "外国历史文选": "methods",
            "中国史学史": "methods",
            "外国史学史": "methods",
            "what is history": "methods",
            "theories and evidence": "methods",
            "中国古代史": "ancient-china",
            "中国古代文学史": "ancient-china",
            "中国古代礼义文明": "ancient-china",
            "中国古代建筑艺术": "ancient-china",
            "科举与唐诗": "ancient-china",
            "大唐兴衰": "ancient-china",
            "唐史四讲": "ancient-china",
            "解读西夏": "ancient-china",
            "中国近现代史": "modern-china",
            "中国近代史": "modern-china",
            "中国现代史": "modern-china",
            "中国当代文学": "modern-china",
            "中国现代文学史": "modern-china",
            "history of foreign relations": "modern-china",
            "世界史": "world-history",
            "世界文明史": "world-history",
            "世界史通论": "world-history",
            "古希腊罗马史": "world-history",
            "中世纪欧洲史": "world-history",
            "古代东方文明": "world-history",
            "欧洲史": "world-history",
            "亚洲史": "world-history",
            "美国史": "world-history",
            "拉丁美洲史": "world-history",
            "非洲史": "world-history",
            "modernity and the state": "world-history",
            "from tea to opium": "world-history",
            "international politics since": "world-history",
            "internationalisation of economic growth": "world-history",
            "博物馆学概论": "archaeology",
            "考古学通论": "archaeology",
            "文化遗产学概论": "archaeology",
            "社会历史调查": "seminars",
            "社会调查与史学研究": "seminars",
            "军事理论": "seminars",
            "学年论文": "seminars",
        },
        "fallback_module": "seminars",
    },

    # ---------------------------------------------------------------------- Philosophy
    "哲学": {
        "modules": [
            {"id": "intro", "name": "哲学导论", "depends_on": []},
            {"id": "chinese-philosophy", "name": "中国哲学", "depends_on": ["intro"]},
            {"id": "ancient-western", "name": "古希腊哲学", "depends_on": ["intro"]},
            {"id": "modern-western", "name": "近代西方哲学", "depends_on": ["ancient-western"]},
            {"id": "contemporary-western", "name": "现代西方哲学", "depends_on": ["modern-western"]},
            {"id": "marxism", "name": "马克思主义哲学", "depends_on": ["intro"]},
            {"id": "logic", "name": "逻辑学", "depends_on": ["intro"]},
            {"id": "ethics-aesthetics", "name": "伦理学与美学", "depends_on": ["intro"]},
            {"id": "philosophy-of-science", "name": "科技哲学", "depends_on": ["contemporary-western", "logic"]},
            {"id": "topics", "name": "专题研讨", "depends_on": ["chinese-philosophy", "contemporary-western", "marxism"]},
        ],
        "course_to_module": {
            "哲学导论": "intro",
            "哲学史": "intro",
            "西方哲学史": "intro",
            "中国哲学史": "intro",
            "马克思主义哲学史": "intro",
            "introduction to philosophy": "intro",
            "history of philosophy": "intro",
            "the big questions": "intro",
            "historical and global perspectives on philosophy": "intro",
            "元哲学": "intro",
            "哲学方法": "intro",
            "philosophy, morals and politics": "intro",
            "中国哲学": "chinese-philosophy",
            "先秦": "chinese-philosophy",
            "孔子": "chinese-philosophy",
            "孟子": "chinese-philosophy",
            "老子": "chinese-philosophy",
            "庄子": "chinese-philosophy",
            "儒家": "chinese-philosophy",
            "道家": "chinese-philosophy",
            "《四书》精读": "chinese-philosophy",
            "《周易本义》精读": "chinese-philosophy",
            "《近思录》精读": "chinese-philosophy",
            "宋明理学": "chinese-philosophy",
            "朱熹": "chinese-philosophy",
            "王阳明": "chinese-philosophy",
            "心学": "chinese-philosophy",
            "中国哲学新视野": "chinese-philosophy",
            "中国古代思想世界": "chinese-philosophy",
            "东西方哲学比较": "chinese-philosophy",
            "儒学与中国社会": "chinese-philosophy",
            "儒释道哲学的人生智慧": "chinese-philosophy",
            "古希腊": "ancient-western",
            "柏拉图": "ancient-western",
            "亚里士多德": "ancient-western",
            "希腊哲学": "ancient-western",
            "《理想国》": "ancient-western",
            "中世纪哲学": "ancient-western",
            "近代西方哲学": "modern-western",
            "笛卡尔": "modern-western",
            "康德": "modern-western",
            "黑格尔": "modern-western",
            "启蒙": "modern-western",
            "休谟哲学": "modern-western",
            "叔本华": "modern-western",
            "尼采": "modern-western",
            "《纯粹理性批判》导论": "modern-western",
            "现代西方哲学": "contemporary-western",
            "分析哲学": "contemporary-western",
            "现象学": "contemporary-western",
            "存在主义": "contemporary-western",
            "维特根斯坦": "contemporary-western",
            "海德格尔": "contemporary-western",
            "语言哲学": "contemporary-western",
            "心灵哲学": "contemporary-western",
            "科学哲学": "contemporary-western",
            "马克思主义哲学": "marxism",
            "马克思": "marxism",
            "恩格斯": "marxism",
            "资本论": "marxism",
            "历史唯物主义": "marxism",
            "辩证唯物主义": "marxism",
            "政治哲学": "marxism",
            "自由主义": "marxism",
            "正义论": "marxism",
            "社群主义": "marxism",
            "social and political philosophy": "marxism",
            "逻辑学": "logic",
            "数理逻辑": "logic",
            "符号逻辑": "logic",
            "一阶逻辑": "logic",
            "公理集合论": "logic",
            "批判性思维": "logic",
            "伦理学": "ethics-aesthetics",
            "道德哲学": "ethics-aesthetics",
            "美学": "ethics-aesthetics",
            "艺术哲学": "ethics-aesthetics",
            "环境伦理": "ethics-aesthetics",
            "the ethics of data and ai": "ethics-aesthetics",
            "value theory": "ethics-aesthetics",
            "技术哲学": "philosophy-of-science",
            "科技哲学": "philosophy-of-science",
            "认知科学哲学": "philosophy-of-science",
            "人工智能哲学": "philosophy-of-science",
            "世界文明中的科学技术": "philosophy-of-science",
            "博物学导论": "philosophy-of-science",
            "philosophy of science": "philosophy-of-science",
            "philosophy of economics": "philosophy-of-science",
            "epistemology": "philosophy-of-science",
            "metaphysics": "philosophy-of-science",
            "哲学研讨会": "topics",
            "精读": "topics",
            "原著": "topics",
            "经典研读": "topics",
            "哲学专业德语": "topics",
            "哲学系实践实习": "topics",
            "宗教学": "topics",
            "佛教": "topics",
            "基督教": "topics",
            "道教": "topics",
            "宗教": "topics",
            "伊斯兰教史": "topics",
        },
        "fallback_module": "topics",
    },

    # ---------------------------------------------------------------------- Chinese
    "汉语言文学": {
        "modules": [
            {"id": "language-basics", "name": "语言基础", "depends_on": []},
            {"id": "ancient-literature", "name": "古代文学", "depends_on": ["language-basics"]},
            {"id": "modern-literature", "name": "现当代文学", "depends_on": ["language-basics"]},
            {"id": "literary-theory", "name": "文学理论", "depends_on": ["ancient-literature", "modern-literature"]},
            {"id": "linguistics", "name": "语言学", "depends_on": ["language-basics"]},
            {"id": "writing", "name": "写作实践", "depends_on": ["literary-theory", "linguistics"]},
        ],
        "course_to_module": {
            "古代汉语": "language-basics",
            "文字学": "language-basics",
            "音韵学": "language-basics",
            "训诂学": "language-basics",
            "现代汉语": "language-basics",
            "语言学概论": "language-basics",
            "先秦文学": "ancient-literature",
            "两汉文学": "ancient-literature",
            "诗经": "ancient-literature",
            "楚辞": "ancient-literature",
            "汉赋": "ancient-literature",
            "魏晋文学": "ancient-literature",
            "唐宋文学": "ancient-literature",
            "唐诗": "ancient-literature",
            "宋词": "ancient-literature",
            "元明清文学": "ancient-literature",
            "戏曲": "ancient-literature",
            "小说": "ancient-literature",
            "红楼梦": "ancient-literature",
            "西游记": "ancient-literature",
            "古代文论": "ancient-literature",
            "文心雕龙": "ancient-literature",
            "诗品": "ancient-literature",
            "现代文学": "modern-literature",
            "鲁迅": "modern-literature",
            "五四": "modern-literature",
            "新文学": "modern-literature",
            "当代文学": "modern-literature",
            "新时期文学": "modern-literature",
            "外国文学": "modern-literature",
            "西方文学": "modern-literature",
            "东方文学": "modern-literature",
            "比较文学": "modern-literature",
            "文学理论": "literary-theory",
            "文艺学": "literary-theory",
            "美学": "literary-theory",
            "文学批评": "literary-theory",
            "中国文学史": "literary-theory",
            "语言学": "linguistics",
            "语法": "linguistics",
            "语义": "linguistics",
            "语用": "linguistics",
            "方言": "linguistics",
            "社会语言学": "linguistics",
            "写作": "writing",
            "创作": "writing",
            "文案": "writing",
            "公文写作": "writing",
        },
        "fallback_module": "literary-theory",
    },

    # ---------------------------------------------------------------------- English
    "英语": {
        "modules": [
            {"id": "language-skills", "name": "语言技能", "depends_on": []},
            {"id": "literature", "name": "英美文学", "depends_on": ["language-skills"]},
            {"id": "linguistics", "name": "语言学", "depends_on": ["language-skills"]},
            {"id": "translation", "name": "翻译", "depends_on": ["language-skills"]},
            {"id": "area-studies", "name": "区域研究", "depends_on": ["literature", "linguistics"]},
            {"id": "practice", "name": "实践", "depends_on": ["translation", "area-studies"]},
        ],
        "course_to_module": {
            "听力": "language-skills",
            "口语": "language-skills",
            "视听说": "language-skills",
            "语音": "language-skills",
            "阅读": "language-skills",
            "写作": "language-skills",
            "英语写作": "language-skills",
            "综合英语": "language-skills",
            "基础英语": "language-skills",
            "英国文学": "literature",
            "英国小说": "literature",
            "莎士比亚": "literature",
            "维多利亚": "literature",
            "美国文学": "literature",
            "美国小说": "literature",
            "美国诗歌": "literature",
            "文学理论": "literature",
            "文学批评": "literature",
            "语言学": "linguistics",
            "语法": "linguistics",
            "语义学": "linguistics",
            "语用学": "linguistics",
            "社会语言学": "linguistics",
            "心理语言学": "linguistics",
            "翻译": "translation",
            "口译": "translation",
            "笔译": "translation",
            "同声传译": "translation",
            "英美文化": "area-studies",
            "美国社会": "area-studies",
            "英国社会": "area-studies",
            "西方文化": "area-studies",
            "商务英语": "area-studies",
            "经贸英语": "area-studies",
            "法律英语": "area-studies",
            "实践": "practice",
            "实习": "practice",
            "毕业论文": "practice",
        },
        "fallback_module": "area-studies",
    },

    # ---------------------------------------------------------------------- Sociology
    "社会学": {
        "modules": [
            {"id": "theory", "name": "社会学理论", "depends_on": []},
            {"id": "methods", "name": "研究方法", "depends_on": ["theory"]},
            {"id": "urban-rural", "name": "城市与农村", "depends_on": ["methods"]},
            {"id": "family-gender", "name": "家庭与性别", "depends_on": ["methods"]},
            {"id": "economic-political", "name": "经济社会学与政治社会学", "depends_on": ["methods"]},
            {"id": "topics", "name": "专题研究", "depends_on": ["urban-rural", "family-gender", "economic-political"]},
        ],
        "course_to_module": {
            "社会学概论": "theory",
            "社会学理论": "theory",
            "古典社会学": "theory",
            "现代社会学": "theory",
            "西方社会学": "theory",
            "社会思想": "theory",
            "社会哲学": "theory",
            "社会研究方法": "methods",
            "社会调查": "methods",
            "定量研究": "methods",
            "定性研究": "methods",
            "统计": "methods",
            "spss": "methods",
            "社会统计": "methods",
            "数据分析": "methods",
            "城市社会学": "urban-rural",
            "农村社会学": "urban-rural",
            "社区": "urban-rural",
            "城镇化": "urban-rural",
            "家庭社会学": "family-gender",
            "性别": "family-gender",
            "婚姻": "family-gender",
            "妇女研究": "family-gender",
            "经济社会学": "economic-political",
            "劳动社会学": "economic-political",
            "消费社会学": "economic-political",
            "政治社会学": "economic-political",
            "文化社会学": "economic-political",
            "宗教社会学": "economic-political",
            "法律社会学": "economic-political",
            "人口社会学": "economic-political",
            "医学社会学": "economic-political",
            "健康社会学": "economic-political",
            "老年社会学": "economic-political",
            "专题": "topics",
            "讨论班": "topics",
            "前沿": "topics",
            "社会运动": "topics",
            "发展": "topics",
        },
        "fallback_module": "topics",
    },

    # ---------------------------------------------------------------------- International Politics
    "国际政治": {
        "modules": [
            {"id": "politics", "name": "政治学基础", "depends_on": []},
            {"id": "ir-theory", "name": "国际关系理论", "depends_on": ["politics"]},
            {"id": "regions", "name": "区域研究", "depends_on": ["ir-theory"]},
            {"id": "security", "name": "安全与外交", "depends_on": ["ir-theory", "regions"]},
            {"id": "international-economy", "name": "国际经济", "depends_on": ["ir-theory"]},
            {"id": "methods", "name": "研究方法", "depends_on": ["security", "international-economy"]},
        ],
        "course_to_module": {
            "政治学": "politics",
            "政治思想": "politics",
            "政治哲学": "politics",
            "比较政治": "politics",
            "国际关系": "ir-theory",
            "国际政治": "ir-theory",
            "外交学概论": "ir-theory",
            "国际关系理论": "ir-theory",
            "国际政治理论": "ir-theory",
            "现实主义": "ir-theory",
            "自由主义": "ir-theory",
            "建构主义": "ir-theory",
            "国际组织": "ir-theory",
            "全球治理": "ir-theory",
            "联合国": "ir-theory",
            "中国外交": "regions",
            "当代中国外交": "regions",
            "中美关系": "regions",
            "美国": "regions",
            "美国政治": "regions",
            "美国外交": "regions",
            "欧洲": "regions",
            "欧盟": "regions",
            "欧洲政治": "regions",
            "亚太": "regions",
            "东亚": "regions",
            "日本": "regions",
            "俄罗斯": "regions",
            "中亚": "regions",
            "东南亚": "regions",
            "中东": "regions",
            "非洲": "regions",
            "拉美": "regions",
            "第三世界": "regions",
            "发展中国家": "regions",
            "国际安全": "security",
            "战略": "security",
            "军备": "security",
            "冲突": "security",
            "战争": "security",
            "恐怖主义": "security",
            "国际经济": "international-economy",
            "国际贸易": "international-economy",
            "国际金融": "international-economy",
            "政治经济学": "international-economy",
            "研究方法": "methods",
            "论文写作": "methods",
            "定量方法": "methods",
            "定性方法": "methods",
        },
        "fallback_module": "regions",
    },

    # ---------------------------------------------------------------------- Economics
    "经济学": {
        "modules": [
            {"id": "math", "name": "经济数学", "depends_on": []},
            {"id": "principles", "name": "微观/宏观经济学", "depends_on": ["math"]},
            {"id": "metrics", "name": "计量经济学", "depends_on": ["principles", "math"]},
            {"id": "applied", "name": "应用经济学", "depends_on": ["metrics"]},
        ],
        "course_to_module": {
            "高等数学": "math",
            "线性代数": "math",
            "概率统计": "math",
            "数学分析": "math",
            "经济数学": "math",
            "微观经济学": "principles",
            "宏观经济学": "principles",
            "产业组织": "principles",
            "博弈论": "principles",
            "经济增长": "principles",
            "经济波动": "principles",
            "政治经济学": "principles",
            "社会主义政治经济学": "principles",
            "资本论": "principles",
            "计量经济学": "metrics",
            "经济计量": "metrics",
            "时间序列": "metrics",
            "因果推断": "metrics",
            "统计学": "metrics",
            "经济统计": "metrics",
            "劳动经济学": "applied",
            "人口经济学": "applied",
            "发展经济学": "applied",
            "产业经济学": "applied",
            "国际贸易": "applied",
            "国际经济学": "applied",
            "公共经济学": "applied",
            "财政学": "applied",
            "货币经济学": "applied",
            "金融经济学": "applied",
            "制度经济学": "applied",
            "行为经济学": "applied",
            "实验经济学": "applied",
            "信息经济学": "applied",
            "中国经济": "applied",
            "世界经济": "applied",
            "专题": "applied",
            "讨论班": "applied",
        },
        "fallback_module": "applied",
    },

    # ---------------------------------------------------------------------- Finance
    "金融学": {
        "modules": [
            {"id": "math", "name": "数学统计", "depends_on": []},
            {"id": "accounting", "name": "会计财务", "depends_on": ["math"]},
            {"id": "corporate-finance", "name": "公司金融", "depends_on": ["accounting"]},
            {"id": "investments", "name": "投资学", "depends_on": ["corporate-finance", "math"]},
            {"id": "markets", "name": "金融市场", "depends_on": ["investments"]},
            {"id": "engineering", "name": "金融工程", "depends_on": ["markets", "math"]},
            {"id": "practice", "name": "实践", "depends_on": ["engineering"]},
        ],
        "course_to_module": {
            "高等数学": "math",
            "线性代数": "math",
            "概率统计": "math",
            "金融中的数学方法": "math",
            "随机分析": "math",
            "会计学": "accounting",
            "财务会计": "accounting",
            "管理会计": "accounting",
            "财务报表分析": "accounting",
            "审计学": "accounting",
            "公司金融": "corporate-finance",
            "公司财务": "corporate-finance",
            "公司理财": "corporate-finance",
            "公司估值": "corporate-finance",
            "投资学": "investments",
            "证券投资": "investments",
            "投资组合": "investments",
            "固定收益证券": "investments",
            "衍生品定价": "investments",
            "金融市场": "markets",
            "金融机构": "markets",
            "货币银行学": "markets",
            "国际金融": "markets",
            "商业银行": "markets",
            "信贷": "markets",
            "风险管理": "markets",
            "金融工程": "engineering",
            "金融衍生工具": "engineering",
            "金融计量": "engineering",
            "量化投资": "engineering",
            "金融时间序列": "engineering",
            "金融科技": "engineering",
            "区块链": "engineering",
            "大数据金融": "engineering",
            "人工智能与投资": "engineering",
            "实践": "practice",
            "实习": "practice",
            "案例": "practice",
            "竞赛": "practice",
        },
        "fallback_module": "markets",
    },

    # ---------------------------------------------------------------------- Business Administration
    "工商管理": {
        "modules": [
            {"id": "foundation", "name": "商科基础", "depends_on": []},
            {"id": "core-management", "name": "核心管理", "depends_on": ["foundation"]},
            {"id": "specialization", "name": "专业方向", "depends_on": ["core-management"]},
            {"id": "entrepreneurship", "name": "创新创业", "depends_on": ["core-management", "specialization"]},
            {"id": "practice", "name": "实践", "depends_on": ["entrepreneurship"]},
        ],
        "course_to_module": {
            "微观经济学": "foundation",
            "宏观经济学": "foundation",
            "发展经济学": "foundation",
            "行为经济学": "foundation",
            "中国经济": "foundation",
            "世界经济": "foundation",
            "高等数学": "foundation",
            "线性代数": "foundation",
            "概率统计": "foundation",
            "计量经济学": "foundation",
            "会计学": "foundation",
            "财务会计": "foundation",
            "管理会计": "foundation",
            "财务报表分析": "foundation",
            "公司金融": "foundation",
            "公司估值": "foundation",
            "营销研究方法": "foundation",
            "营销学": "foundation",
            "消费者行为": "foundation",
            "战略管理": "core-management",
            "企业战略": "core-management",
            "共演战略": "core-management",
            "竞争战略": "core-management",
            "组织行为学": "core-management",
            "人力资源管理": "core-management",
            "组织与管理": "core-management",
            "组织经济学": "core-management",
            "领导力": "core-management",
            "运营管理": "core-management",
            "供应链管理": "core-management",
            "物流管理": "core-management",
            "质量管理": "core-management",
            "仿真模型": "core-management",
            "运筹优化": "core-management",
            "市场营销": "core-management",
            "新媒体营销": "core-management",
            "体育营销": "core-management",
            "品牌管理": "core-management",
            "社会影响力营销": "core-management",
            "互联网时代营销": "core-management",
            "金融市场": "core-management",
            "金融经济学": "core-management",
            "行为金融": "core-management",
            "风险资本": "core-management",
            "中国商务": "specialization",
            "中国社会": "specialization",
            "中国经济": "specialization",
            "国际贸易": "specialization",
            "国际金融": "specialization",
            "中级财务会计": "specialization",
            "高级财务会计": "specialization",
            "高级管理会计": "specialization",
            "金融企业会计": "specialization",
            "内部控制": "specialization",
            "审计学": "specialization",
            "数据驱动": "specialization",
            "机器学习": "specialization",
            "深度学习": "specialization",
            "商务时间序列": "specialization",
            "网络科学": "specialization",
            "因果推断": "specialization",
            "定量推理": "specialization",
            "创业": "entrepreneurship",
            "创新": "entrepreneurship",
            "创办新企业": "entrepreneurship",
            "创业者": "entrepreneurship",
            "新企业": "entrepreneurship",
            "可持续创业": "entrepreneurship",
            "综合商业计划书": "entrepreneurship",
            "产业经济学专题": "practice",
            "华为成功之道": "practice",
            "实践": "practice",
            "案例": "practice",
            "研讨": "practice",
        },
        "fallback_module": "core-management",
    },

    # ---------------------------------------------------------------------- HRM
    "人力资源管理": {
        "modules": [
            {"id": "foundation", "name": "管理基础", "depends_on": []},
            {"id": "ob", "name": "组织行为", "depends_on": ["foundation"]},
            {"id": "hr-core", "name": "人力资源核心", "depends_on": ["ob"]},
            {"id": "compensation", "name": "薪酬绩效", "depends_on": ["hr-core"]},
            {"id": "law-practice", "name": "劳动法/实践", "depends_on": ["compensation"]},
        ],
        "course_to_module": {
            "管理学原理": "foundation",
            "微观经济学": "foundation",
            "宏观经济学": "foundation",
            "会计学": "foundation",
            "高等数学": "foundation",
            "概率统计": "foundation",
            "线性代数": "foundation",
            "组织行为学": "ob",
            "社会心理学": "ob",
            "领导力": "ob",
            "团队": "ob",
            "人力资源管理": "hr-core",
            "人力资源开发": "hr-core",
            "招聘": "hr-core",
            "培训": "hr-core",
            "员工关系": "hr-core",
            "组织设计": "hr-core",
            "工作分析": "hr-core",
            "组织发展": "hr-core",
            "薪酬管理": "compensation",
            "绩效管理": "compensation",
            "绩效考核": "compensation",
            "劳动法": "law-practice",
            "劳动关系": "law-practice",
            "劳动经济学": "law-practice",
            "实践": "law-practice",
            "实习": "law-practice",
            "案例": "law-practice",
            "人力资源战略": "law-practice",
        },
        "fallback_module": "hr-core",
    },

    # ---------------------------------------------------------------------- Public Administration
    "行政管理": {
        "modules": [
            {"id": "foundation", "name": "政治学与公共管理", "depends_on": []},
            {"id": "policy-law", "name": "公共政策/行政法", "depends_on": ["foundation"]},
            {"id": "local-governance", "name": "地方政府/国家治理", "depends_on": ["policy-law"]},
            {"id": "egovernment", "name": "电子政务", "depends_on": ["local-governance"]},
            {"id": "methods", "name": "研究方法/实践", "depends_on": ["egovernment"]},
        ],
        "course_to_module": {
            "政治学": "foundation",
            "政治思想": "foundation",
            "政治哲学": "foundation",
            "比较政治": "foundation",
            "公共管理学": "foundation",
            "行政管理学": "foundation",
            "公共行政": "foundation",
            "经济学": "foundation",
            "公共财政": "foundation",
            "公共经济学": "foundation",
            "公共政策": "policy-law",
            "政策分析": "policy-law",
            "社会政策": "policy-law",
            "行政法": "policy-law",
            "宪法": "policy-law",
            "行政诉讼法": "policy-law",
            "法制": "policy-law",
            "地方政府": "local-governance",
            "市政管理": "local-governance",
            "基层治理": "local-governance",
            "区域治理": "local-governance",
            "国家治理": "local-governance",
            "政府治理": "local-governance",
            "治理理论": "local-governance",
            "电子政务": "egovernment",
            "数字政府": "egovernment",
            "政务大数据": "egovernment",
            "智慧城市": "egovernment",
            "研究方法": "methods",
            "社会调查": "methods",
            "统计": "methods",
            "spss": "methods",
            "实践": "methods",
            "实习": "methods",
            "案例研讨": "methods",
        },
        "fallback_module": "local-governance",
    },

    # ---------------------------------------------------------------------- Law
    "法学": {
        "modules": [
            {"id": "foundation", "name": "法理学/宪法", "depends_on": []},
            {"id": "civil", "name": "民法", "depends_on": ["foundation"]},
            {"id": "criminal", "name": "刑法", "depends_on": ["foundation"]},
            {"id": "procedure", "name": "诉讼法", "depends_on": ["civil", "criminal"]},
            {"id": "commercial", "name": "商法/经济法", "depends_on": ["civil"]},
            {"id": "international", "name": "国际法", "depends_on": ["commercial", "criminal"]},
            {"id": "practice", "name": "法律实务", "depends_on": ["procedure", "international"]},
        ],
        "course_to_module": {
            "法理学": "foundation",
            "法学导论": "foundation",
            "法律方法": "foundation",
            "宪法": "foundation",
            "行政法": "foundation",
            "法制史": "foundation",
            "法律思想史": "foundation",
            "民法总论": "civil",
            "物权法": "civil",
            "债权法": "civil",
            "合同法": "civil",
            "侵权责任法": "civil",
            "婚姻法": "civil",
            "继承法": "civil",
            "家事法": "civil",
            "刑法": "criminal",
            "犯罪学": "criminal",
            "刑事政策": "criminal",
            "民事诉讼法": "procedure",
            "刑事诉讼法": "procedure",
            "行政诉讼法": "procedure",
            "证据法": "procedure",
            "司法鉴定": "procedure",
            "商法": "commercial",
            "公司法": "commercial",
            "证券法": "commercial",
            "保险法": "commercial",
            "破产法": "commercial",
            "经济法": "commercial",
            "竞争法": "commercial",
            "劳动法": "commercial",
            "财税法": "commercial",
            "金融法": "commercial",
            "知识产权": "commercial",
            "著作权": "commercial",
            "专利法": "commercial",
            "商标法": "commercial",
            "国际公法": "international",
            "国际私法": "international",
            "冲突法": "international",
            "国际经济法": "international",
            "wto": "international",
            "国际贸易法": "international",
            "法律实务": "practice",
            "诊所": "practice",
            "模拟法庭": "practice",
            "仲裁": "practice",
            "谈判": "practice",
            "法律文书": "practice",
            "实习": "practice",
            "实践": "practice",
        },
        "fallback_module": "commercial",
    },

    # ---------------------------------------------------------------------- Applied Psychology
    "应用心理学": {
        "modules": [
            {"id": "foundation", "name": "心理学基础", "depends_on": []},
            {"id": "methods", "name": "研究方法/统计测量", "depends_on": ["foundation"]},
            {"id": "domains", "name": "发展/社会/认知心理学", "depends_on": ["methods"]},
            {"id": "clinical", "name": "临床/咨询心理学", "depends_on": ["domains"]},
            {"id": "applied", "name": "应用心理学", "depends_on": ["domains"]},
        ],
        "course_to_module": {
            "普通心理学": "foundation",
            "心理学导论": "foundation",
            "心理学史": "foundation",
            "生理心理学": "foundation",
            "高等数学": "foundation",
            "概率统计": "foundation",
            "线性代数": "foundation",
            "心理学研究方法": "methods",
            "实验心理学": "methods",
            "心理统计学": "methods",
            "心理测量": "methods",
            "心理测验": "methods",
            "测评": "methods",
            "发展心理学": "domains",
            "儿童心理学": "domains",
            "青少年心理学": "domains",
            "老年心理学": "domains",
            "社会心理学": "domains",
            "人格心理学": "domains",
            "认知心理学": "domains",
            "认知神经科学": "domains",
            "知觉": "domains",
            "记忆": "domains",
            "语言心理学": "domains",
            "临床心理学": "clinical",
            "变态心理学": "clinical",
            "心理病理学": "clinical",
            "心理咨询": "clinical",
            "心理治疗": "clinical",
            "团体辅导": "clinical",
            "危机干预": "clinical",
            "工业与组织心理学": "applied",
            "管理心理学": "applied",
            "消费心理学": "applied",
            "广告心理学": "applied",
            "教育心理学": "applied",
            "学校心理学": "applied",
            "学习心理学": "applied",
            "实践": "applied",
            "实习": "applied",
            "案例": "applied",
        },
        "fallback_module": "domains",
    },

    # ---------------------------------------------------------------------- Journalism
    "新闻学": {
        "modules": [
            {"id": "foundation", "name": "新闻传播基础", "depends_on": []},
            {"id": "practice", "name": "新闻实务", "depends_on": ["foundation"]},
            {"id": "media-studies", "name": "媒介研究", "depends_on": ["foundation"]},
            {"id": "digital-media", "name": "数字传播/视听", "depends_on": ["practice", "media-studies"]},
            {"id": "media-business", "name": "传媒经营/实践", "depends_on": ["digital-media"]},
        ],
        "course_to_module": {
            "新闻学概论": "foundation",
            "新闻理论": "foundation",
            "马克思主义新闻观": "foundation",
            "传播学": "foundation",
            "新闻史": "foundation",
            "传播史": "foundation",
            "中外新闻史": "foundation",
            "社会学": "foundation",
            "政治学": "foundation",
            "社会心理学": "foundation",
            "新闻采访": "practice",
            "新闻写作": "practice",
            "新闻编辑": "practice",
            "新闻评论": "practice",
            "新闻摄影": "practice",
            "图片编辑": "practice",
            "媒介研究": "media-studies",
            "媒介批评": "media-studies",
            "媒介伦理": "media-studies",
            "媒介法规": "media-studies",
            "广播电视": "media-studies",
            "电视新闻": "media-studies",
            "播音主持": "media-studies",
            "视听语言": "media-studies",
            "新媒体": "digital-media",
            "数字传播": "digital-media",
            "网络传播": "digital-media",
            "社交媒体": "digital-media",
            "数据新闻": "digital-media",
            "纪录片": "digital-media",
            "影视制作": "digital-media",
            "融媒体": "digital-media",
            "视频": "digital-media",
            "媒介经营": "media-business",
            "传媒经济": "media-business",
            "广告学": "media-business",
            "公共关系": "media-business",
            "品牌传播": "media-business",
            "实践": "media-business",
            "实习": "media-business",
            "工作坊": "media-business",
            "毕业设计": "media-business",
        },
        "fallback_module": "media-studies",
    },

    # ---------------------------------------------------------------------- Archives
    "档案学": {
        "modules": [
            {"id": "foundation", "name": "档案学基础", "depends_on": []},
            {"id": "management", "name": "档案管理", "depends_on": ["foundation"]},
            {"id": "digital", "name": "电子文件/信息化", "depends_on": ["management"]},
            {"id": "preservation", "name": "档案保护/安全", "depends_on": ["management"]},
            {"id": "service", "name": "档案服务与利用", "depends_on": ["digital", "preservation"]},
        ],
        "course_to_module": {
            "档案学概论": "foundation",
            "档案学基础": "foundation",
            "档案学原理": "foundation",
            "信息资源管理": "foundation",
            "信息管理基础": "foundation",
            "档案管理学": "management",
            "档案管理": "management",
            "文书学": "management",
            "文献编纂学": "management",
            "档案编研": "management",
            "电子文件": "digital",
            "电子档案": "digital",
            "数字档案馆": "digital",
            "档案信息化": "digital",
            "档案信息系统": "digital",
            "档案数据库": "digital",
            "档案保护": "preservation",
            "档案修复": "preservation",
            "档案装帧": "preservation",
            "档案安全管理": "preservation",
            "档案法规": "preservation",
            "档案保密": "preservation",
            "档案检索": "service",
            "档案目录学": "service",
            "档案用户服务": "service",
            "档案利用": "service",
            "档案服务": "service",
        },
        "fallback_module": "management",
    },
}


# ---------------------------------------------------------------------------
# Classification helpers
# ---------------------------------------------------------------------------

def _normalize(text: str) -> str:
    """Lower-case and strip whitespace for matching."""
    return (text or "").strip().lower()


def compute_module_levels(modules: list[dict]) -> dict[str, int]:
    """Compute the topological level of each module via Kahn's algorithm.

    Level 0 = source modules with no dependencies.
    A module's level is 1 + max(level of its dependencies).
    """
    module_ids = {m["id"] for m in modules}
    in_degree = {m["id"]: 0 for m in modules}
    adj = {m["id"]: [] for m in modules}

    for m in modules:
        for dep in m.get("depends_on", []):
            if dep in module_ids:
                in_degree[m["id"]] += 1
                adj[dep].append(m["id"])

    levels = {}
    queue = [m["id"] for m in modules if in_degree[m["id"]] == 0]
    for mid in queue:
        levels[mid] = 0

    while queue:
        u = queue.pop(0)
        for v in adj[u]:
            levels[v] = max(levels.get(v, 0), levels[u] + 1)
            in_degree[v] -= 1
            if in_degree[v] == 0:
                queue.append(v)

    # Any remaining modules are part of a cycle; assign them a high level.
    for m in modules:
        if m["id"] not in levels:
            levels[m["id"]] = max(levels.values()) + 1 if levels else 0

    return levels


def _match_course_to_module(course_name: str, course_to_module: dict[str, str], fallback_module: str) -> str:
    """Return the module id whose keyword is the longest substring match."""
    name = _normalize(course_name)
    best_module = fallback_module
    best_len = 0

    for keyword, module_id in course_to_module.items():
        kw = _normalize(keyword)
        if not kw or kw not in name:
            continue
        if len(kw) > best_len:
            best_len = len(kw)
            best_module = module_id

    return best_module


def build_module_roadmap(major_name: str, courses: list[dict], links: list[dict]) -> dict:
    """Build the module dependency roadmap for a major.

    Returns:
        {
          "total_courses": int,
          "total_prerequisite_links": int,
          "modules": [
            {
              "id": str,
              "name": str,
              "level": int,
              "depends_on": [str],
              "courses": [course_dict]
            }
          ],
          "module_links": [{"source": str, "target": str}],
          "courses": [...],
          "links": [...]
        }
    """
    config = ROADMAP_MODULES.get(major_name)
    if not config:
        return {
            "total_courses": len(courses),
            "total_prerequisite_links": len(links),
            "modules": [
                {
                    "id": "all",
                    "name": "全部课程",
                    "level": 0,
                    "depends_on": [],
                    "courses": courses,
                }
            ],
            "module_links": [],
            "courses": courses,
            "links": links,
        }

    modules_config = config["modules"]
    course_to_module = config["course_to_module"]
    fallback_module = config.get("fallback_module", modules_config[0]["id"])

    # Validate fallback module exists.
    module_ids = {m["id"] for m in modules_config}
    if fallback_module not in module_ids:
        fallback_module = modules_config[0]["id"]

    levels = compute_module_levels(modules_config)

    # Assign courses to modules.
    module_courses: dict[str, list[dict]] = {m["id"]: [] for m in modules_config}
    for course in courses:
        module_id = _match_course_to_module(course.get("name", ""), course_to_module, fallback_module)
        if module_id not in module_courses:
            module_id = fallback_module
        module_courses[module_id].append(course)

    modules = []
    for m in modules_config:
        mid = m["id"]
        modules.append({
            "id": mid,
            "name": m["name"],
            "level": levels.get(mid, 0),
            "depends_on": [dep for dep in m.get("depends_on", []) if dep in module_ids],
            "courses": module_courses.get(mid, []),
        })

    module_links = [
        {"source": m["id"], "target": dep}
        for m in modules_config
        for dep in m.get("depends_on", [])
        if dep in module_ids
    ]

    return {
        "total_courses": len(courses),
        "total_prerequisite_links": len(links),
        "modules": modules,
        "module_links": module_links,
        "courses": courses,
        "links": links,
    }
